// Generated by gencpp from file xju_pnc/xju_task.msg
// DO NOT EDIT!


#ifndef XJU_PNC_MESSAGE_XJU_TASK_H
#define XJU_PNC_MESSAGE_XJU_TASK_H

#include <ros/service_traits.h>


#include <xju_pnc/xju_taskRequest.h>
#include <xju_pnc/xju_taskResponse.h>


namespace xju_pnc
{

struct xju_task
{

typedef xju_taskRequest Request;
typedef xju_taskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct xju_task
} // namespace xju_pnc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xju_pnc::xju_task > {
  static const char* value()
  {
    return "aadab28b2111acdfca066c4f4a5419ef";
  }

  static const char* value(const ::xju_pnc::xju_task&) { return value(); }
};

template<>
struct DataType< ::xju_pnc::xju_task > {
  static const char* value()
  {
    return "xju_pnc/xju_task";
  }

  static const char* value(const ::xju_pnc::xju_task&) { return value(); }
};


// service_traits::MD5Sum< ::xju_pnc::xju_taskRequest> should match
// service_traits::MD5Sum< ::xju_pnc::xju_task >
template<>
struct MD5Sum< ::xju_pnc::xju_taskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xju_pnc::xju_task >::value();
  }
  static const char* value(const ::xju_pnc::xju_taskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xju_pnc::xju_taskRequest> should match
// service_traits::DataType< ::xju_pnc::xju_task >
template<>
struct DataType< ::xju_pnc::xju_taskRequest>
{
  static const char* value()
  {
    return DataType< ::xju_pnc::xju_task >::value();
  }
  static const char* value(const ::xju_pnc::xju_taskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xju_pnc::xju_taskResponse> should match
// service_traits::MD5Sum< ::xju_pnc::xju_task >
template<>
struct MD5Sum< ::xju_pnc::xju_taskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xju_pnc::xju_task >::value();
  }
  static const char* value(const ::xju_pnc::xju_taskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xju_pnc::xju_taskResponse> should match
// service_traits::DataType< ::xju_pnc::xju_task >
template<>
struct DataType< ::xju_pnc::xju_taskResponse>
{
  static const char* value()
  {
    return DataType< ::xju_pnc::xju_task >::value();
  }
  static const char* value(const ::xju_pnc::xju_taskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XJU_PNC_MESSAGE_XJU_TASK_H
