#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${ROOT_DIR}/logs"
mkdir -p "${LOG_DIR}"
LOG_FILE="${LOG_DIR}/frontgate.log"
FRONTGATE_PYTHON="${INTERRUPT_FRONTGATE_PYTHON:-}"
ENV_FRONTGATE_PYTHON="${INTERRUPT_FRONTGATE_PYTHON+x}"
ENV_WAKE_WORD_FACTORY="${INTERRUPT_WAKE_WORD_FACTORY+x}"
ENV_SESSION_COMMAND="${INTERRUPT_FRONTGATE_SESSION_COMMAND+x}"
ENV_SESSION_TIMEOUT="${INTERRUPT_FRONTGATE_SESSION_TIMEOUT+x}"
ORIG_FRONTGATE_PYTHON="${INTERRUPT_FRONTGATE_PYTHON-}"
ORIG_WAKE_WORD_FACTORY="${INTERRUPT_WAKE_WORD_FACTORY-}"
ORIG_SESSION_COMMAND="${INTERRUPT_FRONTGATE_SESSION_COMMAND-}"
ORIG_SESSION_TIMEOUT="${INTERRUPT_FRONTGATE_SESSION_TIMEOUT-}"

if [[ -z "${FRONTGATE_PYTHON}" ]]; then
  source "${ROOT_DIR}/libexec/python_env.sh"
  interrupt_activate_python_env "${ROOT_DIR}"
  FRONTGATE_PYTHON="python"
fi

exec > >(tee -a "${LOG_FILE}") 2>&1
echo "===== $(date '+%F %T') run_frontgate_session.sh ====="
echo "frontgate python: ${FRONTGATE_PYTHON}"

if [[ -f "${ROOT_DIR}/.env.local" ]]; then
  set -a
  source "${ROOT_DIR}/.env.local"
  set +a
fi

if [[ -f "${ROOT_DIR}/.env" ]]; then
  set -a
  source "${ROOT_DIR}/.env"
  set +a
fi

export INTERRUPT_FRONTGATE_ENABLE_WAKE_ACK="${INTERRUPT_FRONTGATE_ENABLE_WAKE_ACK:-1}"
export INTERRUPT_FRONTGATE_ENABLE_WAKE_INTRO="${INTERRUPT_FRONTGATE_ENABLE_WAKE_INTRO:-1}"
export INTERRUPT_FRONTGATE_ENABLE_ROOM_READY_ACK="${INTERRUPT_FRONTGATE_ENABLE_ROOM_READY_ACK:-1}"
export INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_ZH="${INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_ZH:-请问您有什么需求呢}"
export INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_YUE="${INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_YUE:-請問您有咩需求呢}"
export INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_EN="${INTERRUPT_FRONTGATE_ROOM_READY_ACK_TEXT_EN:-How can I help you?}"
export INTERRUPT_FRONTGATE_WATCHDOG_ENABLED="${INTERRUPT_FRONTGATE_WATCHDOG_ENABLED:-1}"
export INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_ZH="${INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_ZH:-你好，机器人|你好机器人|你好，機器人|你好機器人|机器人，你好|机器人你好|機器人，你好|機器人你好}"
export INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_YUE="${INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_YUE:-你好，機器人|你好機器人|你好，机器人|你好机器人|機器人，你好|機器人你好|机器人，你好|机器人你好}"
export INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_EN="${INTERRUPT_FRONTGATE_WATCHDOG_PREFIX_EN:-Hello, Robot|Hello Robot|Hi, Robot|Hi Robot|Hey, Robot|Hey Robot|Oh, Robot|Oh Robot}"
export INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_ZH="${INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_ZH:-你好}"
export INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_YUE="${INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_YUE:-你好}"
export INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_EN="${INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_EN:-Hello|Hi|Hey|Oh}"
export INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_ZH="${INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_ZH:-机器人|機器人}"
export INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_YUE="${INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_YUE:-機器人|机器人}"
export INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_EN="${INTERRUPT_FRONTGATE_WATCHDOG_ROBOT_TERM_EN:-Robot}"
export INTERRUPT_FRONTGATE_WATCHDOG_FOLLOWUP_WINDOW_S="${INTERRUPT_FRONTGATE_WATCHDOG_FOLLOWUP_WINDOW_S:-6}"
export INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_WINDOW_S="${INTERRUPT_FRONTGATE_WATCHDOG_PENDING_PREFIX_WINDOW_S:-3.5}"
export INTERRUPT_RTC_TEXT_INPUT_ONLY="${INTERRUPT_RTC_TEXT_INPUT_ONLY:-1}"
export INTERRUPT_RTC_TRANSCRIBE_SILENCE_S="${INTERRUPT_RTC_TRANSCRIBE_SILENCE_S:-1.1}"
export INTERRUPT_RTC_TRANSCRIBE_MIN_AUDIO_S="${INTERRUPT_RTC_TRANSCRIBE_MIN_AUDIO_S:-0.6}"

if [[ -n "${ENV_FRONTGATE_PYTHON}" ]]; then
  export INTERRUPT_FRONTGATE_PYTHON="${ORIG_FRONTGATE_PYTHON}"
fi
if [[ -n "${ENV_WAKE_WORD_FACTORY}" ]]; then
  export INTERRUPT_WAKE_WORD_FACTORY="${ORIG_WAKE_WORD_FACTORY}"
fi
if [[ -n "${ENV_SESSION_COMMAND}" ]]; then
  export INTERRUPT_FRONTGATE_SESSION_COMMAND="${ORIG_SESSION_COMMAND}"
fi
if [[ -n "${ENV_SESSION_TIMEOUT}" ]]; then
  export INTERRUPT_FRONTGATE_SESSION_TIMEOUT="${ORIG_SESSION_TIMEOUT}"
fi

FACTORY="${INTERRUPT_WAKE_WORD_FACTORY:-${ORIG_WAKE_WORD_FACTORY:-src.mock_wakeword:factory}}"
SESSION_COMMAND="${INTERRUPT_FRONTGATE_SESSION_COMMAND:-${ORIG_SESSION_COMMAND:-${ROOT_DIR}/run_local_voice_agent.sh}}"
SESSION_TIMEOUT="${INTERRUPT_FRONTGATE_SESSION_TIMEOUT:-${ORIG_SESSION_TIMEOUT:-0}}"

echo "frontgate factory: ${FACTORY}"
echo "frontgate session command: ${SESSION_COMMAND}"
echo "frontgate session timeout: ${SESSION_TIMEOUT}"

ARGS=(
  --factory "${FACTORY}"
  --session-command "${SESSION_COMMAND}"
  --session-timeout "${SESSION_TIMEOUT}"
)

if [[ $# -gt 0 ]]; then
  ARGS+=("$@")
fi

exec "${FRONTGATE_PYTHON}" "${ROOT_DIR}/tools/wakeword_session_frontgate.py" "${ARGS[@]}"
