// Generated by gencpp from file fastlio/MapConvert.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_MAPCONVERT_H
#define FASTLIO_MESSAGE_MAPCONVERT_H

#include <ros/service_traits.h>


#include <fastlio/MapConvertRequest.h>
#include <fastlio/MapConvertResponse.h>


namespace fastlio
{

struct MapConvert
{

typedef MapConvertRequest Request;
typedef MapConvertResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapConvert
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::MapConvert > {
  static const char* value()
  {
    return "27938b198ec2a6b94cdc450d4db81e6d";
  }

  static const char* value(const ::fastlio::MapConvert&) { return value(); }
};

template<>
struct DataType< ::fastlio::MapConvert > {
  static const char* value()
  {
    return "fastlio/MapConvert";
  }

  static const char* value(const ::fastlio::MapConvert&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::MapConvertRequest> should match
// service_traits::MD5Sum< ::fastlio::MapConvert >
template<>
struct MD5Sum< ::fastlio::MapConvertRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::MapConvert >::value();
  }
  static const char* value(const ::fastlio::MapConvertRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::MapConvertRequest> should match
// service_traits::DataType< ::fastlio::MapConvert >
template<>
struct DataType< ::fastlio::MapConvertRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::MapConvert >::value();
  }
  static const char* value(const ::fastlio::MapConvertRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::MapConvertResponse> should match
// service_traits::MD5Sum< ::fastlio::MapConvert >
template<>
struct MD5Sum< ::fastlio::MapConvertResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::MapConvert >::value();
  }
  static const char* value(const ::fastlio::MapConvertResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::MapConvertResponse> should match
// service_traits::DataType< ::fastlio::MapConvert >
template<>
struct DataType< ::fastlio::MapConvertResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::MapConvert >::value();
  }
  static const char* value(const ::fastlio::MapConvertResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_MAPCONVERT_H
