// Generated by gencpp from file fastlio/SaveMapRequest.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SAVEMAPREQUEST_H
#define FASTLIO_MESSAGE_SAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastlio
{
template <class ContainerAllocator>
struct SaveMapRequest_
{
  typedef SaveMapRequest_<ContainerAllocator> Type;

  SaveMapRequest_()
    : save_path()
    , resolution(0.0)  {
    }
  SaveMapRequest_(const ContainerAllocator& _alloc)
    : save_path(_alloc)
    , resolution(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _save_path_type;
  _save_path_type save_path;

   typedef float _resolution_type;
  _resolution_type resolution;





  typedef boost::shared_ptr< ::fastlio::SaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastlio::SaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMapRequest_

typedef ::fastlio::SaveMapRequest_<std::allocator<void> > SaveMapRequest;

typedef boost::shared_ptr< ::fastlio::SaveMapRequest > SaveMapRequestPtr;
typedef boost::shared_ptr< ::fastlio::SaveMapRequest const> SaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastlio::SaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastlio::SaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastlio::SaveMapRequest_<ContainerAllocator1> & lhs, const ::fastlio::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.save_path == rhs.save_path &&
    lhs.resolution == rhs.resolution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastlio::SaveMapRequest_<ContainerAllocator1> & lhs, const ::fastlio::SaveMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastlio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastlio::SaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastlio::SaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastlio::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a96f2e72de5be58c9ecaa2c3fbfbb12a";
  }

  static const char* value(const ::fastlio::SaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa96f2e72de5be58cULL;
  static const uint64_t static_value2 = 0x9ecaa2c3fbfbb12aULL;
};

template<class ContainerAllocator>
struct DataType< ::fastlio::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastlio/SaveMapRequest";
  }

  static const char* value(const ::fastlio::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastlio::SaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string save_path\n"
"float32 resolution\n"
;
  }

  static const char* value(const ::fastlio::SaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastlio::SaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save_path);
      stream.next(m.resolution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastlio::SaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastlio::SaveMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "save_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.save_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTLIO_MESSAGE_SAVEMAPREQUEST_H
