// Generated by gencpp from file fastlio/SaveMap.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SAVEMAP_H
#define FASTLIO_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <fastlio/SaveMapRequest.h>
#include <fastlio/SaveMapResponse.h>


namespace fastlio
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::SaveMap > {
  static const char* value()
  {
    return "2ecd66ba01bbd96308e3355e33bda01e";
  }

  static const char* value(const ::fastlio::SaveMap&) { return value(); }
};

template<>
struct DataType< ::fastlio::SaveMap > {
  static const char* value()
  {
    return "fastlio/SaveMap";
  }

  static const char* value(const ::fastlio::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::SaveMapRequest> should match
// service_traits::MD5Sum< ::fastlio::SaveMap >
template<>
struct MD5Sum< ::fastlio::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SaveMap >::value();
  }
  static const char* value(const ::fastlio::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SaveMapRequest> should match
// service_traits::DataType< ::fastlio::SaveMap >
template<>
struct DataType< ::fastlio::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::SaveMap >::value();
  }
  static const char* value(const ::fastlio::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::SaveMapResponse> should match
// service_traits::MD5Sum< ::fastlio::SaveMap >
template<>
struct MD5Sum< ::fastlio::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SaveMap >::value();
  }
  static const char* value(const ::fastlio::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SaveMapResponse> should match
// service_traits::DataType< ::fastlio::SaveMap >
template<>
struct DataType< ::fastlio::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::SaveMap >::value();
  }
  static const char* value(const ::fastlio::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_SAVEMAP_H
