// Generated by gencpp from file fastlio/SlamStartRequest.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMSTARTREQUEST_H
#define FASTLIO_MESSAGE_SLAMSTARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastlio
{
template <class ContainerAllocator>
struct SlamStartRequest_
{
  typedef SlamStartRequest_<ContainerAllocator> Type;

  SlamStartRequest_()
    : code(0)  {
    }
  SlamStartRequest_(const ContainerAllocator& _alloc)
    : code(0)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::fastlio::SlamStartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastlio::SlamStartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlamStartRequest_

typedef ::fastlio::SlamStartRequest_<std::allocator<void> > SlamStartRequest;

typedef boost::shared_ptr< ::fastlio::SlamStartRequest > SlamStartRequestPtr;
typedef boost::shared_ptr< ::fastlio::SlamStartRequest const> SlamStartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastlio::SlamStartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastlio::SlamStartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastlio::SlamStartRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamStartRequest_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastlio::SlamStartRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamStartRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastlio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamStartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamStartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamStartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamStartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamStartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamStartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastlio::SlamStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e8de1acec506dc927ef4d2e8193b594";
  }

  static const char* value(const ::fastlio::SlamStartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e8de1acec506dc9ULL;
  static const uint64_t static_value2 = 0x27ef4d2e8193b594ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastlio::SlamStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastlio/SlamStartRequest";
  }

  static const char* value(const ::fastlio::SlamStartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastlio::SlamStartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 code\n"
;
  }

  static const char* value(const ::fastlio::SlamStartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastlio::SlamStartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamStartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastlio::SlamStartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastlio::SlamStartRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMSTARTREQUEST_H
