// Generated by gencpp from file fastlio/SlamStart.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMSTART_H
#define FASTLIO_MESSAGE_SLAMSTART_H

#include <ros/service_traits.h>


#include <fastlio/SlamStartRequest.h>
#include <fastlio/SlamStartResponse.h>


namespace fastlio
{

struct SlamStart
{

typedef SlamStartRequest Request;
typedef SlamStartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamStart
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::SlamStart > {
  static const char* value()
  {
    return "70c3acd228da7b83ec6f69864540ea91";
  }

  static const char* value(const ::fastlio::SlamStart&) { return value(); }
};

template<>
struct DataType< ::fastlio::SlamStart > {
  static const char* value()
  {
    return "fastlio/SlamStart";
  }

  static const char* value(const ::fastlio::SlamStart&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::SlamStartRequest> should match
// service_traits::MD5Sum< ::fastlio::SlamStart >
template<>
struct MD5Sum< ::fastlio::SlamStartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamStart >::value();
  }
  static const char* value(const ::fastlio::SlamStartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamStartRequest> should match
// service_traits::DataType< ::fastlio::SlamStart >
template<>
struct DataType< ::fastlio::SlamStartRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamStart >::value();
  }
  static const char* value(const ::fastlio::SlamStartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::SlamStartResponse> should match
// service_traits::MD5Sum< ::fastlio::SlamStart >
template<>
struct MD5Sum< ::fastlio::SlamStartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamStart >::value();
  }
  static const char* value(const ::fastlio::SlamStartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamStartResponse> should match
// service_traits::DataType< ::fastlio::SlamStart >
template<>
struct DataType< ::fastlio::SlamStartResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamStart >::value();
  }
  static const char* value(const ::fastlio::SlamStartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMSTART_H
