// Generated by gencpp from file fastlio/SlamHold.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMHOLD_H
#define FASTLIO_MESSAGE_SLAMHOLD_H

#include <ros/service_traits.h>


#include <fastlio/SlamHoldRequest.h>
#include <fastlio/SlamHoldResponse.h>


namespace fastlio
{

struct SlamHold
{

typedef SlamHoldRequest Request;
typedef SlamHoldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamHold
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::SlamHold > {
  static const char* value()
  {
    return "70c3acd228da7b83ec6f69864540ea91";
  }

  static const char* value(const ::fastlio::SlamHold&) { return value(); }
};

template<>
struct DataType< ::fastlio::SlamHold > {
  static const char* value()
  {
    return "fastlio/SlamHold";
  }

  static const char* value(const ::fastlio::SlamHold&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::SlamHoldRequest> should match
// service_traits::MD5Sum< ::fastlio::SlamHold >
template<>
struct MD5Sum< ::fastlio::SlamHoldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamHold >::value();
  }
  static const char* value(const ::fastlio::SlamHoldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamHoldRequest> should match
// service_traits::DataType< ::fastlio::SlamHold >
template<>
struct DataType< ::fastlio::SlamHoldRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamHold >::value();
  }
  static const char* value(const ::fastlio::SlamHoldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::SlamHoldResponse> should match
// service_traits::MD5Sum< ::fastlio::SlamHold >
template<>
struct MD5Sum< ::fastlio::SlamHoldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamHold >::value();
  }
  static const char* value(const ::fastlio::SlamHoldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamHoldResponse> should match
// service_traits::DataType< ::fastlio::SlamHold >
template<>
struct DataType< ::fastlio::SlamHoldResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamHold >::value();
  }
  static const char* value(const ::fastlio::SlamHoldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMHOLD_H
