// Generated by gencpp from file fastlio/SlamReLoc.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMRELOC_H
#define FASTLIO_MESSAGE_SLAMRELOC_H

#include <ros/service_traits.h>


#include <fastlio/SlamReLocRequest.h>
#include <fastlio/SlamReLocResponse.h>


namespace fastlio
{

struct SlamReLoc
{

typedef SlamReLocRequest Request;
typedef SlamReLocResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamReLoc
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::SlamReLoc > {
  static const char* value()
  {
    return "aad2501aad91b362151568ebb4dede7c";
  }

  static const char* value(const ::fastlio::SlamReLoc&) { return value(); }
};

template<>
struct DataType< ::fastlio::SlamReLoc > {
  static const char* value()
  {
    return "fastlio/SlamReLoc";
  }

  static const char* value(const ::fastlio::SlamReLoc&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::SlamReLocRequest> should match
// service_traits::MD5Sum< ::fastlio::SlamReLoc >
template<>
struct MD5Sum< ::fastlio::SlamReLocRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamReLoc >::value();
  }
  static const char* value(const ::fastlio::SlamReLocRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamReLocRequest> should match
// service_traits::DataType< ::fastlio::SlamReLoc >
template<>
struct DataType< ::fastlio::SlamReLocRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamReLoc >::value();
  }
  static const char* value(const ::fastlio::SlamReLocRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::SlamReLocResponse> should match
// service_traits::MD5Sum< ::fastlio::SlamReLoc >
template<>
struct MD5Sum< ::fastlio::SlamReLocResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamReLoc >::value();
  }
  static const char* value(const ::fastlio::SlamReLocResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamReLocResponse> should match
// service_traits::DataType< ::fastlio::SlamReLoc >
template<>
struct DataType< ::fastlio::SlamReLocResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamReLoc >::value();
  }
  static const char* value(const ::fastlio::SlamReLocResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMRELOC_H
