// Generated by gencpp from file fastlio/SlamRelocCheckResponse.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMRELOCCHECKRESPONSE_H
#define FASTLIO_MESSAGE_SLAMRELOCCHECKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastlio
{
template <class ContainerAllocator>
struct SlamRelocCheckResponse_
{
  typedef SlamRelocCheckResponse_<ContainerAllocator> Type;

  SlamRelocCheckResponse_()
    : status(false)  {
    }
  SlamRelocCheckResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SlamRelocCheckResponse_

typedef ::fastlio::SlamRelocCheckResponse_<std::allocator<void> > SlamRelocCheckResponse;

typedef boost::shared_ptr< ::fastlio::SlamRelocCheckResponse > SlamRelocCheckResponsePtr;
typedef boost::shared_ptr< ::fastlio::SlamRelocCheckResponse const> SlamRelocCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator1> & lhs, const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator1> & lhs, const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastlio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastlio/SlamRelocCheckResponse";
  }

  static const char* value(const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamRelocCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastlio::SlamRelocCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastlio::SlamRelocCheckResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMRELOCCHECKRESPONSE_H
