// Generated by gencpp from file fastlio/SlamReLocRequest.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMRELOCREQUEST_H
#define FASTLIO_MESSAGE_SLAMRELOCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastlio
{
template <class ContainerAllocator>
struct SlamReLocRequest_
{
  typedef SlamReLocRequest_<ContainerAllocator> Type;

  SlamReLocRequest_()
    : pcd_path()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  SlamReLocRequest_(const ContainerAllocator& _alloc)
    : pcd_path(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pcd_path_type;
  _pcd_path_type pcd_path;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::fastlio::SlamReLocRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastlio::SlamReLocRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlamReLocRequest_

typedef ::fastlio::SlamReLocRequest_<std::allocator<void> > SlamReLocRequest;

typedef boost::shared_ptr< ::fastlio::SlamReLocRequest > SlamReLocRequestPtr;
typedef boost::shared_ptr< ::fastlio::SlamReLocRequest const> SlamReLocRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastlio::SlamReLocRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastlio::SlamReLocRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastlio::SlamReLocRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamReLocRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pcd_path == rhs.pcd_path &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastlio::SlamReLocRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamReLocRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastlio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamReLocRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamReLocRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamReLocRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38125fdf079f43774b2d35b7a4aafc69";
  }

  static const char* value(const ::fastlio::SlamReLocRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38125fdf079f4377ULL;
  static const uint64_t static_value2 = 0x4b2d35b7a4aafc69ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastlio/SlamReLocRequest";
  }

  static const char* value(const ::fastlio::SlamReLocRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pcd_path\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::fastlio::SlamReLocRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pcd_path);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamReLocRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastlio::SlamReLocRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastlio::SlamReLocRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pcd_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pcd_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMRELOCREQUEST_H
