// Generated by gencpp from file fastlio/SlamRelocCheckRequest.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMRELOCCHECKREQUEST_H
#define FASTLIO_MESSAGE_SLAMRELOCCHECKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fastlio
{
template <class ContainerAllocator>
struct SlamRelocCheckRequest_
{
  typedef SlamRelocCheckRequest_<ContainerAllocator> Type;

  SlamRelocCheckRequest_()
    : code(false)  {
    }
  SlamRelocCheckRequest_(const ContainerAllocator& _alloc)
    : code(false)  {
  (void)_alloc;
    }



   typedef uint8_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlamRelocCheckRequest_

typedef ::fastlio::SlamRelocCheckRequest_<std::allocator<void> > SlamRelocCheckRequest;

typedef boost::shared_ptr< ::fastlio::SlamRelocCheckRequest > SlamRelocCheckRequestPtr;
typedef boost::shared_ptr< ::fastlio::SlamRelocCheckRequest const> SlamRelocCheckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator1> & lhs, const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fastlio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8542f1d39cbea04214f9c91a3bc0357";
  }

  static const char* value(const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8542f1d39cbea04ULL;
  static const uint64_t static_value2 = 0x214f9c91a3bc0357ULL;
};

template<class ContainerAllocator>
struct DataType< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fastlio/SlamRelocCheckRequest";
  }

  static const char* value(const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool code\n"
;
  }

  static const char* value(const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamRelocCheckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fastlio::SlamRelocCheckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fastlio::SlamRelocCheckRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMRELOCCHECKREQUEST_H
