// Generated by gencpp from file fastlio/SlamRelocCheck.msg
// DO NOT EDIT!


#ifndef FASTLIO_MESSAGE_SLAMRELOCCHECK_H
#define FASTLIO_MESSAGE_SLAMRELOCCHECK_H

#include <ros/service_traits.h>


#include <fastlio/SlamRelocCheckRequest.h>
#include <fastlio/SlamRelocCheckResponse.h>


namespace fastlio
{

struct SlamRelocCheck
{

typedef SlamRelocCheckRequest Request;
typedef SlamRelocCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SlamRelocCheck
} // namespace fastlio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fastlio::SlamRelocCheck > {
  static const char* value()
  {
    return "6fa8ef0c716a8f69e2ee4f999bd02a6e";
  }

  static const char* value(const ::fastlio::SlamRelocCheck&) { return value(); }
};

template<>
struct DataType< ::fastlio::SlamRelocCheck > {
  static const char* value()
  {
    return "fastlio/SlamRelocCheck";
  }

  static const char* value(const ::fastlio::SlamRelocCheck&) { return value(); }
};


// service_traits::MD5Sum< ::fastlio::SlamRelocCheckRequest> should match
// service_traits::MD5Sum< ::fastlio::SlamRelocCheck >
template<>
struct MD5Sum< ::fastlio::SlamRelocCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamRelocCheck >::value();
  }
  static const char* value(const ::fastlio::SlamRelocCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamRelocCheckRequest> should match
// service_traits::DataType< ::fastlio::SlamRelocCheck >
template<>
struct DataType< ::fastlio::SlamRelocCheckRequest>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamRelocCheck >::value();
  }
  static const char* value(const ::fastlio::SlamRelocCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fastlio::SlamRelocCheckResponse> should match
// service_traits::MD5Sum< ::fastlio::SlamRelocCheck >
template<>
struct MD5Sum< ::fastlio::SlamRelocCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fastlio::SlamRelocCheck >::value();
  }
  static const char* value(const ::fastlio::SlamRelocCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fastlio::SlamRelocCheckResponse> should match
// service_traits::DataType< ::fastlio::SlamRelocCheck >
template<>
struct DataType< ::fastlio::SlamRelocCheckResponse>
{
  static const char* value()
  {
    return DataType< ::fastlio::SlamRelocCheck >::value();
  }
  static const char* value(const ::fastlio::SlamRelocCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FASTLIO_MESSAGE_SLAMRELOCCHECK_H
